### ISSUE TITLE
Node School link is dead

### ISSUE THREAD

**Issue by vivekimsit** [cyberwizardinstitute/externalresources#5]

**Comment by kevincoleman** [comment]
Works for me.

**Comment by vivekimsit** [comment]
@kevincoleman The hyperlink provided in the docs is not right.

**Comment by kevincoleman** [comment]
Ahhh, I see. I page-searched and found the other reference to nodeschool.

**Comment by kevincoleman** [comment]
Sorry about that. Fixed.

Thanks for keeping an eye on these. 👍
